[project]
name = "pymgcv"
authors = [{ name = "danielward27", email = "danielward27@outlook.com" }]
description = "pymgcv: Generalized additive models using mgcv, in Python."
requires-python = ">= 3.11, <= 3.12"
version = "0.0.0"

# CI fails on 3.13 currently.

keywords = ["generalized additive models", "GAMs"]
license = { file = "LICENSE" }
readme = "README.md"
dependencies = ["rpy2>=3.6.1"]

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[tool.pytest.ini_options]
addopts = "--markdown-docs"

[project.optional-dependencies]
dev = [
    "pytest",
    "ruff",
    "hippogriffe",
    "mkdocs",
    "mkdocs-material",
    "mkdocs-ipynb",
    "mkdocstrings[python]",
    "pymdown-extensions",
    "griffe-inherited-docstrings",
    "ipykernel",
    "pytest-markdown-docs",
    "mdit-py-plugins",
    "markdown-it-py",
]
[tool.pytest.ini_options]
pythonpath = ["."]

# ------------------- pixi config --------------------#

[tool.pixi.dependencies]
r-base = "*"
r-mgcv = "*"
setuptools = "*"
cffi = ">=1.17.1,<2"     # https://github.com/rpy2/rpy2/issues/739
numpy = ">=2.2.5,<3"
pandas = ">=2.2.3,<3"
matplotlib = ">=3.10,<4"

[tool.pixi.pypi-dependencies]
pymgcv = { path = ".", editable = true }

[tool.pixi.pypi-options]
no-build-isolation = ["rpy2"]

[tool.pixi.workspace]
channels = ["conda-forge"]
platforms = ["linux-64", "osx-64", "osx-arm64"]


[tool.pixi.environments]
dev = ["dev"]

# ----------------- ruff config -------------------#
[tool.ruff]
include = ["*.py", "*.pyi", "**/pyproject.toml", "*.ipynb"]

[tool.ruff.lint]
select = ["E", "F", "B", "D", "COM", "I", "UP", "TRY004", "RET", "PT", "FBT"]

[tool.ruff.lint.pydocstyle]
convention = "google"
