[project]
authors = [{ name = "Daniel Ward", email = "danielward27@outlook.com" }]
classifiers = [
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Natural Language :: English",
    "Programming Language :: Python :: 3",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Topic :: Scientific/Engineering :: Information Analysis",
    "Topic :: Scientific/Engineering :: Mathematics",
]
dependencies = ["numpy", "pandas", "rpy2"]
description = "pymgcv: Generalized additive models using mgcv, in Python."
keywords = ["generalized additive models", "GAMs"]
license = { file = "LICENSE" }
name = "pymgcv"
readme = "README.md"
requires-python = ">=3.10"
version = "0.0.0"

[project.urls]
repository = "https://github.com/danielward27/pymgcv"
# documentation = "https://danielward27.github.io/pymgcv/index.html"

[project.optional-dependencies]
dev = [
    "pytest",
    "beartype",
    "pytest-beartype",
    "ruff",
    "hippogriffe",
    "mkdocs",
    "mkdocs-material",
    "mkdocstrings[python]",
    "pymdown-extensions",
    "griffe-inherited-docstrings",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.pytest.ini_options]
pythonpath = ["."]
beartype_packages = 'pymgcv'

[tool.ruff]
include = ["*.py", "*.pyi", "**/pyproject.toml", "*.ipynb"]

[tool.ruff.lint]
select = ["E", "F", "B", "D", "COM", "I", "UP", "TRY004", "RET", "PT", "FBT"]
ignore = ["D101", "D105", "D107", "B028", "COM812", "F722"]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.per-file-ignores]
"tests/*" = ["D"]
"*.ipynb" = ["D"]
"__init__.py" = ["D"]
