[project]
name = "pymgcv"
requires-python = ">= 3.11, <= 3.12"
version = "0.0.0"

dependencies = ["rpy2"]


[project.optional-dependencies]
dev = ["pytest"]

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]


[tool.pytest.ini_options]
pythonpath = ["."]

# ------------------- pixi config --------------------#

[tool.pixi.dependencies]
r-base = "*"
cffi = ">=1.17.1,<2" # https://github.com/rpy2/rpy2/issues/739
setuptools = ">=80.1.0,<81"


[tool.pixi.pypi-dependencies]
pymgcv = { path = ".", editable = true }

[tool.pixi.pypi-options]
no-build-isolation = ["rpy2"]

[tool.pixi.workspace]
channels = ["conda-forge"]
platforms = ["linux-64"]


[tool.pixi.environments]
dev = ["dev"]
