name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Test:
    name: Tests
    runs-on: ["ubuntu-latest", "macos-latest", "windows-latest"]
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: "3.10"

      - name: Install dependencies
        shell: bash -el # Ensures the Conda environment is activated
        run: |
          conda install rpy2 R -y
          pip install -e .[dev]

      - name: Run pytest
        shell: bash -el # Ensures the Conda environment is activated
        run: pytest
