name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

defaults:
  run:
    shell: bash -l {0}

jobs:
  Test:
    name: Tests
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        py_ver: ["3.10"]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: "3.12" # tests run with $py_ver

      - name: Install dependencies
        run: |
          conda create -n pkg_test -c conda-forge python=$PY_VER 'rpy2' 'r-mgcv'
          conda activate pkg_test
          pip install -e .[dev]

      - name: Run pytest
        run: |
          conda activate pkg_test
          pytest
