name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Test:
    name: Tests
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        py_ver: ["3.10"]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: "3.12" # tests run with $py_ver

      - name: Install dependencies
        shell: bash -el {0} # Ensures the Conda environment is activated
        run: |
          conda create -n pkg_test -c conda-forge python=$PY_VER 'rpy2' 'r-mgcv'
          conda activate pkg_test
          # conda install -c conda-forge r-base r-mgcv -y
          # pip install rpy2
          pip install -e .[dev]

      - name: Run pytest
        shell: bash -el {0}

        run: |
          conda activate pkg_test
          pytest
