name: test

on:
  push:
    branches:
      - linker_mwe

jobs:
  Test:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: prefix-dev/setup-pixi@v0.8.5
        with:
          environments: dev
